ERROR:TeleBot:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:Exception traceback:
Traceback (most recent call last):
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:Exception traceback:
Traceback (most recent call last):
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:Exception traceback:
Traceback (most recent call last):
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

INFO:root:Starting LinkedIn job scrape for "estagio" in "Brazil"...
INFO:root:Scrolling to bottom of page 1...
INFO:root:Show more button not found, stopping scrolling...
INFO:root:Starting LinkedIn job scrape for "estagio" in "Brazil"...
INFO:root:Scrolling to bottom of page 1...
INFO:root:Show more button not found, stopping scrolling...
INFO:root:Scraped "Estágio em Atendimento Receptivo (Customer Success..." at EBAC - Escola Britânica de Artes Criativas e Tecnologia in São Paulo, SP...
INFO:root:Scraped "Estágio em Análise de Dados (Vaga Híbrida)" at dti digital in Belo Horizonte, MG...
INFO:root:Scraped "Estágio em Análise de Dados (Vaga Híbrida)" at dti digital in Belo Horizonte, MG...
INFO:root:Scraped "Estágio - Análise de Dados" at Dafiti in São Paulo, SP...
INFO:root:Scraped "SESI/PE - CÓD. 441 ESTÁGIO EM PEDAGOGIA (VASCO DA ..." at Sistema FIEPE in Recife, PE...
INFO:root:Scraped "Estágio em Inteligência de Mercado" at EPTV in Campinas, SP...
INFO:root:Scraped "Estágio financeiro" at Tera in São Paulo, SP...
INFO:root:Scraped "Estágio de Planejamento Supply Chain" at Mobly in São Paulo, SP...
INFO:root:Scraped "Estágio em Desenvolvimento de Software (Vaga Híbri..." at dti digital in Belo Horizonte, MG...
INFO:root:Scraped "Estagiário em Desenvolvimento Front-End [Remoto]" at Shakers Agência & Consultoria in São Paulo e Região...
INFO:root:Closing driver
INFO:root:Returning from function
ERROR:TeleBot:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:Exception traceback:
Traceback (most recent call last):
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 1214, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 676, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/__init__.py", line 648, in get_updates
    json_updates = apihelper.get_updates(
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 328, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/herbeth-lks/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

